# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'

- script: |
    echo package and scan the Python App
    export VERACODE_API_KEY_ID=$(VERACODE_API_ID)
    export VERACODE_API_KEY_SECRET=$(VERACODE_API_KEY)
    curl -sSL https://tools.veracode.com/veracode-cli/install | sh
    mkdir verascan
    ./veracode package -s ./ -a -o ./verascan
  displayName: 'Package Python'

- task: Bash@3
  displayName: 'Perform Veracode SCA scan on kotlin portion'
  inputs:
     targetType: 'inline'
     script: |
          export SRCCLR_SCM_URI=https://github.com/christyson/Verademo-Python
          export SRCCLR_API_TOKEN="$(SRCCLR_API_TOKEN)"
          export SRCCLR_SCM_REF=master
          export SRCCLR_SCM_REF_TYPE=branch
          export SRCCLR_SCM_REV=123456
          curl -sSL https://download.sourceclear.com/ci.sh | bash -s -- scan --update-advisor
- task: Veracode@3
  displayName: 'Run a Veracode SAST Scan'
  inputs:
      ConnectionDetailsSelection: 'Service Connection'
      AnalysisService: 'Veracode'
      veracodeAppProfile: 'ADO_$(system.teamProject)'
      version: '$(build.buildNumber)'
      filepath: '$(System.DefaultWorkingDirectory)/verascan'
      createProfile: true
      importResults: true
      maximumWaitTime: '360'

