name: Veracode SCA Scan

on: 
  push:
    paths-ignore:
      - "README.md"
  schedule:
    - cron: 15 14 * * 6

jobs:
  veracode-sca-task:
    runs-on: ubuntu-latest
    name: Scan repository for Issues

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run Veracode SCA
        env:
          SRCCLR_API_TOKEN: ${{ secrets.SRCCLR_API_TOKEN }}
        uses: Lerer/veracode-sca@v1.0.1 
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          quick: true
          create-issues: false 
          fail-on-cvss: 3
